# Generated by Django 4.2.7 on 2025-04-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Stripe Payment')], max_length=15),
        ),
    ]
