# Generated by Django 4.2.7 on 2025-04-29 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_rename_state_property_county_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='available',
        ),
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Under Maintenance')], default='available', max_length=20),
        ),
    ]
