# Generated by Django 4.2.7 on 2025-04-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='monthly_rent',
            field=models.DecimalField(decimal_places=2, help_text='Monthly rent in £', max_digits=10),
        ),
        migrations.AlterField(
            model_name='lease',
            name='security_deposit',
            field=models.DecimalField(decimal_places=2, help_text='Security deposit in £', max_digits=10),
        ),
    ]
